routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route:: resource('/','ProdutoController');
Route::resource('product','ProdutoController');

app/Categoria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    protected $fillable = ['DESCRICAO'];
    protected $guarded = ['COD_CATEGORIA', 'created_at', 'update_at'];
    protected $primaryKey = 'COD_CATEGORIA';

    protected $table = 'categoria';
}

app/Produto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produto extends Model
{
    protected $fillable = ['DESCRICAO','COD_CATEGORIA'];
    protected $guarded = ['COD_PRODUTO', 'created_at', 'update_at'];
    protected $primaryKey = 'COD_PRODUTO';

    protected $table = 'produto';
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CategoriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CategoriaController extends Controller
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProdutoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Produto;
use App\Categoria;
USE DB;
class ProdutoController extends Controller
{   
    //Index Pagina de Produtos
    public function index() {

        $produtos = DB::table('produto')
                    ->join('categoria', 'categoria.COD_CATEGORIA','=','produto.COD_CATEGORIA')
                    ->select('produto.COD_PRODUTO','produto.DESCRICAO','produto.COD_CATEGORIA','categoria.DESCRICAO as DESC_CATEGORIA')
                    ->get();

        $total = Produto::all()->count();
        return view('list-produtos', compact('produtos', 'total'));
    }

    //View formulario Cadastro de Produto
    public function create() {
        $categorias = Categoria::all();
        return view('include-produto', compact('categorias'));
    }

    //Cadastrando Produtos No Banco
    public function store(Request $request) {
        $product = new Produto;
        $product->DESCRICAO = $request->description;
        $product->COD_CATEGORIA =  $request->COD_CATEGORIA;
        $product->save();
        return redirect()->route('product.index')->with('message', 'Produto criado com sucesso!');
    }

    public function show($id) {
        //
    }

    //View Formulario Editar Produtos
    public function edit($id) {
        $product = Produto::findOrFail($id);
        $categorias = Categoria::all();
        return view('alter-produto', compact('product','categorias'));
    }

    //Update dos Produtos no banco
    public function update(Request $request, $id) {
        $product = Produto::findOrFail($id);
        $product->DESCRICAO = $request->description;
        $product->COD_CATEGORIA = $request->COD_CATEGORIA;
        $product->save();
        return redirect()->route('product.index')->with('message', 'Produto alterado com sucesso!');
    }

    //Deletar Produto
    public function destroy($id) {
        $product = Produto::findOrFail($id);
        $product->delete();
        return redirect()->route('product.index')->with('message', 'Produto excluído com sucesso!');
    }

}

resources/views/alter-produto.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Comercial Laravel</title>

        <!-- Favicon -->
        <link href="{{URL::asset('img/favicon.ico')}}" rel="shortcut icon">

        <!-- Fonts -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

        <!-- Styles -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link href="{{URL::asset('css/style.css')}}" rel="stylesheet" type="text/css" />

        <!-- JavaScript -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="{{URL::asset('js/ajax.js')}}"></script>
    </head>
    <body>

        <div id="line-one">
            <div class="container">
                <div class="row">
                    <div class="col-md-12" id="center">
                        <h1><b>Produto</b></h1>
                        <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li><a href="">Panel</a></li>
                            <li><a href="{{route('product.index')}}">Produtos</a></li>
                            <li class="active">Alteração</li>
                        </ol>
                    </div>
                </div>
                <div class="row">
                    <br>
                    <h4 id="center"><b>ALTERAÇÃO DOS DADOS DO PRODUTO</b></h4>
                    <br>
                    <form method="post"
                          action="{{route('product.update', $product->COD_PRODUTO)}}"
                          enctype="multipart/form-data">
                        {!! method_field('put') !!}
                        {{ csrf_field() }}

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="description">Descrição</label>
                                <input type="text" name="description"
                                       class="form-control"
                                       value="{{$product->DESCRICAO}}"
                                       required>
                            </div>
                        </div>
                        
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="description">Categorias</label>
                                <select name="COD_CATEGORIA" class="form-control">
                                     @foreach($categorias as $categoria)
                                    <option value="{{$categoria->COD_CATEGORIA}}" @if ($categoria->COD_CATEGORIA == $product->COD_CATEGORIA) {{ 'selected' }} @endif> {{$categoria->DESCRICAO}}</option>
                                     @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <button type="reset" class="btn btn-default">
                                Limpar
                            </button>
                            <button type="submit"
                                    class="btn btn-warning" id="black">
                                Alterar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/include-produto.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>CRUD TEST SPOT</title>

        <!-- Favicon -->
        <link href="{{URL::asset('img/favicon.ico')}}" rel="shortcut icon">

        <!-- Fonts -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

        <!-- Styles -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link href="{{URL::asset('css/style.css')}}" rel="stylesheet" type="text/css" />

        <!-- JavaScript -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="{{URL::asset('js/ajax.js')}}"></script>
    </head>
    <body>

        <div id="line-one">
            <div class="container">
                <div class="row">
                    <div class="col-md-12" id="center">
                        <h1><b>Produto</b></h1>
                        <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li><a href="">Panel</a></li>
                            <li><a href="{{route('product.index')}}">Produtos</a></li>
                            <li class="active">Cadastro</li>
                        </ol>
                    </div>
                </div>
                <div class="row">
                    <br>
                    <h4 id="center"><b>CADASTRO DOS DADOS DO PRODUTO</b></h4>
                    <br>
                    <form method="post"
                          action="{{route('product.store')}}"
                          enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="description">Descrição do Produto</label>
                                <input type="text" name="description"
                                       class="form-control"
                                       required>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="description">Categorias</label>
                                <select name="COD_CATEGORIA" class="form-control">
                                     @foreach($categorias as $categoria)
                                    <option value="{{$categoria->COD_CATEGORIA}}">{{$categoria->DESCRICAO}}</option>
                                     @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <button type="reset" class="btn btn-default">
                                Limpar
                            </button>
                            <button type="submit"
                                    class="btn btn-warning" id="black">
                                Cadastrar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/list-produtos.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>CRUD TEST SPOT</title>

        <!-- Favicon -->
        <link href="{{URL::asset('img/favicon.ico')}}" rel="shortcut icon">

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

        <!-- Styles -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link href="{{URL::asset('css/style.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{URL::asset('css/lightbox.css')}}" rel="stylesheet" type="text/css" />

        <!-- JavaScript -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="{{URL::asset('js/ajax.js')}}"></script>
        <script src="{{URL::asset('js/lightbox.js')}}"></script>
    </head>
    <body>

        @if (session('message'))
        <div class="alert alert-success alert-dismissible">
            <a href="#" class="close"
               data-dismiss="alert"
               aria-label="close">&times;</a>
            {{ session('message') }}
        </div>
        @endif
        <div id="line-one">
            <div class="container">
                <div class="row">
                    <div class="col-md-12" id="center">
                        <h1><b>Produtos</b></h1>
                        <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li class="active">Produtos</li>
                        </ol>
                        <br>
                        <a href="{{route('product.create')}}"
                           class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Adicionar Produto</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <br />
                        <h4 id="center"><b>PRODUTOS CADASTRADOS ({{$total}})</b></h4>
                        <br>
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th id="center">Código</th>
                                        <th>Descrição</th>
                                        <th>Categoria</th>
                                        <th id="center">Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($produtos as $produto)
                                    <tr>
                                        <td id="center">{{$produto->COD_PRODUTO}}</td>
                                        <td title="Descrição">{{$produto->DESCRICAO}}</td>
                                        <td title="Descrição">{{$produto->DESC_CATEGORIA}}</td>
                                        <td id="center">
                                            <a href="{{route('product.edit', $produto->COD_PRODUTO)}}"
                                               data-toggle="tooltip"
                                               data-placement="top"
                                               title="Alterar"><i class="fa fa-pencil"></i></a>
                                            &nbsp;<form style="display: inline-block;" method="POST"
                                                        action="{{route('product.destroy', $produto->COD_PRODUTO)}}"
                                                        data-toggle="tooltip" data-placement="top"
                                                        title="Excluir"
                                                        onsubmit="return confirm('Confirma exclusão?')">
                                                {{method_field('DELETE')}}{{ csrf_field() }}
                                                <button type="submit" style="background-color: #fff">
                                                    <a><i class="fa fa-trash-o"></i></a>
                                                </button></form></td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <img src="{{URL::asset('img/subir.png')}}"
                 id="up"
                 style="display: none;"
                 alt="Ícone Subir ao Topo"
                 title="Subir ao topo?">
            </body>
            </html>